# Generated by Django 4.2.1 on 2023-07-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked', to='Solo_App.user'),
        ),
        migrations.AddField(
            model_name='car',
            name='rent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars', models.ManyToManyField(related_name='order_car', to='Solo_App.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solo_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Solo_App.user')),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars', models.ManyToManyField(related_name='cart_cars', to='Solo_App.car')),
            ],
        ),
    ]
